### ISSUE TITLE
Make Aimbot better 

### ISSUE THREAD

**Issue by kakahost** [FCSSensai/Rook-Scripts-Public-Beta#1]
Make it able to choose custom aimbot button, multipe bones to aim and tratiors detector

**Comment by kakahost** [comment]
Make Fov setting

**Comment by thenamesjay** [comment]
You already ARE able to choose the custom aimbot button, and bones.

We will be adding a traitor detector eventually, it's on the list.
As for FOV, we have a FOV setting, but you may mean FOVAimbot, in which case, we're working on that as well.

**Comment by kakahost** [comment]
> You already ARE able to choose the custom aimbot button, and bones.
> 
> We will be adding a traitor detector eventually, it's on the list. As for FOV, we have a FOV setting, but you may mean FOVAimbot, in which case, we're working on that as well.

Make NPC aimbot please) I will close this section.

**Comment by kakahost** [comment]
And Aim by crosshair, distance not the best idea

**Comment by thenamesjay** [comment]
Intended features, but ones I have zero help to complete... 
It'll take time.
