### ISSUE TITLE
How do you install/use this?

### ISSUE THREAD

**Issue by imoliverokay** [FCSSensai/Rook-Scripts-Public-Beta#2]
I cannot figure out how to install this!

**Comment by thenamesjay** [comment]
You place it in the Lua folder and run it as a client side script

**Comment by imoliverokay** [comment]
> You place it in the Lua folder and run it as a client side script

is it called autorun?

**Comment by thenamesjay** [comment]
It's just garrysmod/GarrysMod/Lua
