### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by SuperAssBeater420** [FCSSensai/Rook-Scripts-Public-Beta#4]
I put it in the lua folder but i didn't know how to open it in game. I also tried to throw it in autorun and client. Am i supposed to press a button or a commans?

**Comment by SuperAssBeater420** [comment]
I figured it out! just through it in the rook beta lua into the "lua" folder. To be more exact I took the rook_scripts_v3_beta.lua out of its folder and put it in the "lua" folder.

**Comment by thenamesjay** [comment]
> I figured it out! just through it in the rook beta lua into the "lua" folder. To be more exact I took the rook_scripts_v3_beta.lua out of its folder and put it in the "lua" folder.

Amazing work, leaving this for others future reference.
